<?php
return [
    'categoryProduct' => [
        'title' => true,
        'model' => '\App\Models\CategoryProduct',
        'excelfile' => 'category_product.xlsx',
        'selectField' => [
            0 => "id",
            1 => "name",
            2 =>  "slug",
            3 => "icon_path",
            4 => "avatar_path",
            5 => "active",
            6 => "parent_id",
            7 => "admin_id",
            8 => "created_at",
            9 => "updated_at",
        ],
        'importField' => [
           // 0 => "id",
            1 => "name",
            2 =>  "slug",
            3 => "icon_path",
            4 => "avatar_path",
            5 => "active",
            6 => "parent_id",
            7 => "admin_id",
           // 8 => "created_at",
           // 9 => "updated_at",
        ],
        'titleField' => [
            "id" => "id",
            "name" => "name",
            "slug" =>  "slug",
            "icon_path" => "icon_path",
            "avatar_path" => "avatar_path",
            "active" => "active",
            "parent_id" => "parent_id",
            "admin_id" => "admin_id",
            "created_at" => "created_at",
            "updated_at" => "updated_at",
        ],
    ],
    'categoryPost' => [
        'title' => true,
        'model' => '\App\Models\CategoryPost',
        'excelfile' => 'category_post.xlsx',
        'selectField' => [
            0 => "id",
            1 => "name",
            2 =>  "slug",
            3 => "icon_path",
            4 => "avatar_path",
            5 => "active",
            6 => "parent_id",
            7 => "admin_id",
            8 => "created_at",
            9 => "updated_at",
        ],
        'importField' => [
           // 0 => "id",
            1 => "name",
            2 =>  "slug",
            3 => "icon_path",
            4 => "avatar_path",
            5 => "active",
            6 => "parent_id",
            7 => "admin_id",
           // 8 => "created_at",
           // 9 => "updated_at",
        ],
        'titleField' => [
            "id" => "id",
            "name" => "name",
            "slug" =>  "slug",
            "icon_path" => "icon_path",
            "avatar_path" => "avatar_path",
            "active" => "active",
            "parent_id" => "parent_id",
            "admin_id" => "admin_id",
            "created_at" => "created_at",
            "updated_at" => "updated_at",
        ],
    ],
    'product' => [
        'title' => true,
        'model' => '\App\Models\Product',
        'excelfile' => 'product.xlsx',

        'selectField' => [
            0 => "id",
            1 => "name",
            2 =>  "slug",
            3 => "price",
            4 => "sale",
            5 => "hot",
            6 => "pay",
            7 => "number",
            8 => "warranty",
            9 => "view",
            10 =>  "description",
            11 =>  "avatar_path",
            12 =>  "description_seo",
            13 =>  "title_seo",
            14 =>  "content",
            15 =>  "active",
            16 =>  "category_id",
            17 =>  "suppiler_id",
            18 =>  "admin_id",
            19 =>  "created_at",
            20 =>  "updated_at",
        ],
        'importField' => [
            1 => "name",
            2 =>  "slug",
            3 => "price",
            4 => "sale",
            5 => "hot",
            6 => "pay",
            7 => "number",
            8 => "warranty",
            9 => "view",
            10 =>  "description",
            11 =>  "avatar_path",
            12 =>  "description_seo",
            13 =>  "title_seo",
            14 =>  "content",
            15 =>  "active",
            16 =>  "category_id",
            17 =>  "suppiler_id",
            18 =>  "admin_id",
            //  19 =>  "created_at",
            //  20 =>  "updated_at",
        ],
        'titleField' => [
            "name" => "name",
            "slug"=>  "slug",
            "price"=> "price",
            "sale" => "sale",
            "hot"=> "hot",
            "pay" => "pay",
            "number" => "number",
            "warranty" => "warranty",
            "view" => "view",
            "description" =>  "description",
            "avatar_path" =>  "avatar_path",
            "description_seo" =>  "description_seo",
            "title_seo" =>  "title_seo",
            "content" =>  "content",
            "active" =>  "active",
            "category_id" =>  "category_id",
            "suppiler_id" =>  "suppiler_id",
            "admin_id" =>  "admin_id",
            //  "created_at" =>  "created_at",
            //  "updated_at" =>  "updated_at",
        ],
    ],
    'post' => [
        'title' => true,
        'model' => '\App\Models\Post',
        'excelfile' => 'post.xlsx',

        'selectField' => [
            0 => "id",
            1 => "name",
            2 =>  "slug",
            3 => "description",
            4 => "content",
            5 => "avatar_path",
            6 => "description_seo",
            7 => "title_seo",
            8 => "view",
            9 => "hot",
            10 =>  "active",
            11 =>  "category_id",
            12 =>  "admin_id",
            13 =>  "created_at",
            14 =>  "updated_at",
        ],
        'importField' => [
            1 => "name",
            2 =>  "slug",
            3 => "description",
            4 => "content",
            5 => "avatar_path",
            6 => "description_seo",
            7 => "title_seo",
            8 => "view",
            9 => "hot",
            10 =>  "active",
            11 =>  "category_id",
            12 =>  "admin_id",
            //  13 =>  "created_at",
            //  14 =>  "updated_at",
        ],
        'titleField' => [
            "name" => "name",
            "slug"=>  "slug",
            "description"=> "description",
            "content" => "content",
            "avatar_path"=> "avatar_path",
            "description_seo" => "description_seo",
            "title_seo" => "title_seo",
            "warranty" => "warranty",
            "view" => "view",
            "hot" =>  "hot",
            "active" =>  "active",
            "category_id" =>  "category_id",
            "title_seo" =>  "title_seo",
            "content" =>  "content",
            "active" =>  "active",
            "category_id" =>  "category_id",
            "admin_id" =>  "admin_id",
            //  "created_at" =>  "created_at",
            //  "updated_at" =>  "updated_at",
        ],
    ],

];
